apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-flights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-flights
  template:
    metadata:
      labels:
        app: mongo-flights
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-flights-storage
              mountPath: /data/db
      volumes:
        - name: mongo-flights-storage
          persistentVolumeClaim:
            claimName: mongo-flights-pvc
