apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-flights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-flights
  template:
    metadata:
      labels:
        app: mongo-flights
    spec:
      containers:
        - name: mongo-flights
          image: mongo:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-flights
spec:
  selector:
    app: mongo-flights
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017