apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-airline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-airline
  template:
    metadata:
      labels:
        app: mysql-airline
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          ports:
            - containerPort: 3307
          volumeMounts:
            - name: mysql-airline-storage  # Corrected volume name
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-airline-storage  # Corrected volume name
          persistentVolumeClaim:
            claimName: mysql-airline-pvc  # Corrected PVC name
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-airline
spec:
  selector:
    app: mysql-airline
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307  # Corrected targetPort to match the containerPort in the deployment
  type: NodePort
