apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-airline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-airline
  template:
    metadata:
      labels:
        app: mysql-airline
    spec:
      containers:
        - name: mysql-airline
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-airline
spec:
  selector:
    app: mysql-airline
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306