apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-airline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-airline
  template:
    metadata:
      labels:
        app: mysql-airline
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
            - name: MYSQLX_PORT
              value: "3307"
          ports:
            - containerPort: 3307
          volumeMounts:
            - name: mysql-airline-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-airline-storage
          persistentVolumeClaim:
            claimName: mysql-airline-pvc
