apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-airport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-airport
  template:
    metadata:
      labels:
        app: mysql-airport
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
            - hostPort: 3306
          volumeMounts:
            - name: mysql-airport-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-airport-storage
          persistentVolumeClaim:
            claimName: mysql-airport-pvc
