name: flight-services
services:
  mongo-flights:
    image: mongo:latest
    volumes:
      - mongodb_flight_data:/data/db
    command: []

  mysql-airport:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - mysql_airport_data:/var/lib/mysql
    ports:
      - 3306:3306

  mysql-airline:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - mysql_airline_data:/var/lib/mysql
    ports:
      - 3307:3306

  flight-service:
    image: iliassafiullin/flight-service-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-flights

  airline-service:
    image: iliassafiullin/airline-service-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8082:8082
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-airline
      MYSQL_DB_PORT: 3307
      MYSQL_DB_TIMEOUT: 300

  airport-service:
    image: iliassafiullin/airport-service-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8081:8081
    environment:
      FLIGHT_SERVICE_BASEURL: flight-service:8080
      AIRLINE_SERVICE_BASEURL: airline-service:8082
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-airport
      MYSQL_DB_PORT: 3306
      MYSQL_DB_TIMEOUT: 300

  api-gateway:
    image: iliassafiullin/gateway-api-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8083:8083
    environment:
      FLIGHT_SERVICE_BASEURL: flight-service:8080
      AIRPORT_SERVICE_BASEURL: airline-service:8082

volumes:
  mongodb_flight_data:
  mysql_airport_data:
  mysql_airline_data:
