name: flight-services
namespace: isafiullin

services:
  mongo_flights:
    image: mongo:latest
    volumes:
      - mongodb_flight_data:/data/db

  mysql_airport:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - mysql_airport_data:/var/lib/mysql

  mysql_airline:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - mysql_airline_data:/var/lib/mysql

  flight_service:
    image: iliassafiullin/flight-service-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8080:8080

  airline_service:
    image: iliassafiullin/airline-service-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8082:8082

  airport_service:
    image: iliassafiullin/airport-service-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8081:8081

  api-gateway:
    image: iliassafiullin/gateway-api-image:latest
    command: []
    volumes:
      - .:/app
    ports:
      - 8083:8083

volumes:
  mongodb_flight_data:
  mysql_airport_data:
  mysql_airline_data:
