server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: flight-service
          uri: http://${FLIGHT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/flights/create
            - Method=POST
          filters:
            - SetPath=/api/flight/create

        - id: flight-service-all
          uri: http://${FLIGHT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/flights
            - Method=GET
          filters:
            - SetPath=/api/flight/all

        - id: flight-service-delete
          uri: http://${FLIGHT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/flights/delete/${id}
            - Method=DELETE
          filters:
            - SetPath=/api/flight/delete/${id}

        - id: airline-service-all
          uri: http://${AIRLINE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/airlines
            - Method=GET
          filters:
            - SetPath=/api/airline/all

        - id: airline-service-cancel
          uri: http://${AIRLINE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/airlines/cancel/**
            - Method=PUT
          filters:
            - SetPath=/api/airline/cancelFlight/${id}

        - id: airport-service
          uri: http://${AIRPORT_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/airports
            - Method=GET
          filters:
            - SetPath=/api/airport/all

        - id: airport-service-schedule-flight
          uri: http://${AIRLINE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/airlines/schedule/**
            - Method=POST
          filters:
            - SetPath=/api/airline/scheduleFlight/${id}